# Generated by Django 5.2.6 on 2026-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_consultation_follow_up_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="request_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
