# Generated by Django 5.2.6 on 2026-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_payment_request_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustment",
            name="request_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="request_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="refund",
            name="request_key",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
