# Generated by Django 5.2.6 on 2026-10-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_patientaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='terms_version_accepted',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PatientVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(max_length=120)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('claim_patient', 'Claim Patient'), ('password_reset', 'Password Reset')], max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('matched_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_challenges', to='core.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['contact', 'purpose', 'is_used'], name='chal_contact_purp_idx')],
            },
        ),
    ]
