# Generated by Django 5.2.6 on 2026-10-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_patientaccount_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='id_document_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='identity_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patientverificationchallenge',
            name='salt',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
