# Generated by Django 5.2.6 on 2026-10-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_patient_health_record_release_and_private_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(default='General', max_length=60)),
                ('description', models.TextField()),
                ('highlight', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HospitalFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='General Information', max_length=80)),
                ('highlight_tag', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='icon_name',
            field=models.CharField(blank=True, default='medical_services', max_length=40),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='ambulance_phone',
            field=models.CharField(blank=True, default='108', max_length=32),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='ambulance_phone_display',
            field=models.CharField(blank=True, default='108', max_length=64),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='city',
            field=models.CharField(blank=True, default='Lucknow, Uttar Pradesh', max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='emergency_phone',
            field=models.CharField(blank=True, default='102', max_length=32),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='emergency_phone_display',
            field=models.CharField(blank=True, default='102 / 108', max_length=64),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='landmark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='maps_query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='reception_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='reception_phone_display',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='consultation_fee',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='languages',
            field=models.CharField(blank=True, default='Hindi, English', max_length=120),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='opd_room',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='opd_schedule',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='qualifications',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
