# Generated by Django 5.2.6 on 2026-10-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hospitalfacility_hospitalfaq_department_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eligibility', models.TextField(blank=True)),
                ('fasting_instructions', models.TextField(blank=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('included_services', models.ManyToManyField(related_name='health_packages', to='core.service')),
            ],
            options={
                'ordering': ('name', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='health_package_price_nonnegative'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='health_package_valid_dates')],
            },
        ),
    ]
