# Generated by Django 5.2.6 on 2026-10-06 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hospitalfacility_hospitalfaq_department_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('provider_type', models.CharField(choices=[('insurer', 'Insurer'), ('tpa', 'TPA')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbhaIntegrationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_reference', models.CharField(max_length=160, unique=True)),
                ('purpose', models.TextField()),
                ('granted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('external_link_reference', models.CharField(blank=True, max_length=160)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abha_consents', to='core.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_reference', models.CharField(max_length=160)),
                ('policy_reference', models.CharField(max_length=160)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='unverified', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='core.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='core.insuranceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('authoritative_source', models.CharField(blank=True, max_length=160)),
                ('authority_reference', models.CharField(blank=True, max_length=160)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='core.insurancepolicy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='insurancepolicy',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='insurance_policy_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='insuranceverification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('result', 'verified'), _negated=True), models.Q(('authoritative_source__gt', ''), ('authority_reference__gt', ''), ('performed_by__isnull', False), ('performed_at__isnull', False)), _connector='OR'), name='verified_insurance_has_authority'),
        ),
    ]
