# Generated by Django 5.2.6 on 2026-10-06 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hospitalfacility_hospitalfaq_department_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('doctor_consultation', 'Doctor Consultation'), ('nursing_care', 'Nursing & In-Patient'), ('emergency_care', 'Emergency Care'), ('pharmacy_lab', 'Pharmacy & Lab'), ('overall_experience', 'Overall Experience')], default='doctor_consultation', max_length=32)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('is_anonymous_public', models.BooleanField(default=True, help_text='If published, do not expose patient name publicly.')),
                ('status', models.CharField(choices=[('pending', 'Pending Moderation'), ('published', 'Published'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by Patient')], default='pending', max_length=16)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_feedback', to='core.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_feedbacks', to='core.staffprofile')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.patient')),
            ],
            options={
                'permissions': [('can_moderate_feedback', 'Can moderate patient feedback')],
                'indexes': [models.Index(fields=['status', 'doctor'], name='feedback_status_doc_idx'), models.Index(fields=['patient', 'status'], name='feedback_patient_status_idx'), models.Index(fields=['created_at'], name='feedback_created_idx')],
            },
        ),
    ]
