# Generated by Django 5.2.6 on 2026-10-06 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_healthpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('audience', models.CharField(default='patients', max_length=80)),
                ('language', models.CharField(default='en', max_length=12)),
                ('references', models.JSONField(blank=True, default=list)),
                ('emergency_disclaimer', models.TextField(default='For emergency symptoms, seek emergency care immediately.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_provider', models.CharField(blank=True, max_length=80)),
                ('ai_model', models.CharField(blank=True, max_length=80)),
                ('ai_prompt_version', models.CharField(blank=True, max_length=40)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_health_content', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_health_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('publish_healthcontent', 'Can clinically approve and publish health content')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('expires_on__gte', models.F('effective_from')), _connector='OR'), name='health_content_valid_dates'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(('reviewer__isnull', False), ('reviewed_at__isnull', False)), _connector='OR'), name='published_health_content_reviewed')],
            },
        ),
    ]
