# Generated by Django 5.2.6 on 2026-10-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hospitalfacility_hospitalfaq_department_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCheckInPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_check_in_passes', to='core.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_check_in_passes', to='core.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'expires_at'], name='qr_patient_expiry_idx')],
            },
        ),
    ]
