# Generated by Django 5.2.6 on 2026-10-06 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_digitalcheckinpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_amount', models.CharField(max_length=60)),
                ('dose_unit', models.CharField(default='tablet', max_length=40)),
                ('target_times', models.JSONField(default=list, help_text="List of HH:MM strings in local 24h format, e.g. ['08:00', '20:00']")),
                ('meal_relation', models.CharField(choices=[('before_meal', 'Before Meal'), ('after_meal', 'After Meal'), ('with_meal', 'With Meal'), ('no_relation', 'No Relation')], default='no_relation', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_medication_schedules', to='core.staffprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_schedules', to='core.patient')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='core.prescriptionitem')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField(help_text='Expected scheduled dose timestamp in UTC')),
                ('action', models.CharField(choices=[('taken', 'Taken'), ('skipped', 'Skipped')], default='taken', max_length=16)),
                ('logged_at', models.DateTimeField()),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='core.medicationschedule')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='medication_schedule_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='medicationdoselog',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_time'), name='unique_schedule_scheduled_time_dose'),
        ),
    ]
