# Generated by Django 5.2.6 on 2026-10-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text="Indicates whether this is the doctor's primary specialty.")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='core.staffprofile')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialty_doctors', to='core.specialty')),
            ],
            options={
                'verbose_name': 'Doctor Specialty',
                'verbose_name_plural': 'Doctor Specialties',
            },
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', through='core.DoctorSpecialty', to='core.specialty'),
        ),
        migrations.AddIndex(
            model_name='doctorspecialty',
            index=models.Index(fields=['doctor', 'is_primary'], name='doc_spec_prim_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorspecialty',
            constraint=models.UniqueConstraint(fields=('doctor', 'specialty'), name='unique_doctor_specialty'),
        ),
    ]
