# Generated by Django 5.2.6 on 2026-10-08 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_doctorspecialty_staffprofile_specialties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for recurring clinic availability (0=Monday, 6=Sunday).')),
                ('start_time', models.TimeField(help_text='Session start time in hospital local time.')),
                ('end_time', models.TimeField(help_text='Session end time in hospital local time.')),
                ('opd_room', models.CharField(blank=True, help_text='Optional room or clinical chamber for this session.', max_length=64)),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=15, help_text='Duration per appointment slot in minutes.')),
                ('max_patients', models.PositiveSmallIntegerField(default=20, help_text='Maximum appointment capacity for this session.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this recurring schedule is active.')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.staffprofile')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'weekday', 'is_active'], name='doc_sched_day_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='doctor_schedule_valid_time_range')],
            },
        ),
    ]
