# Generated by Django 5.2.6 on 2026-10-08 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=160, unique=True)),
                ('category', models.CharField(choices=[('pathology', 'Pathology / Laboratory'), ('radiology', 'Radiology / Imaging'), ('cardiology', 'Cardiology Diagnostics'), ('neurology', 'Neurology Diagnostics'), ('pulmonology', 'Pulmonology Diagnostics'), ('other', 'Other Diagnostic')], db_index=True, default='pathology', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('preparation_instructions', models.TextField(blank=True, help_text='Patient instructions (e.g. 10-12 hours fasting, withhold medications, etc.).')),
                ('sample_type', models.CharField(blank=True, help_text='Specimen or modality required (e.g. Whole Blood, Serum, X-Ray, MRI).', max_length=80)),
                ('turnaround_time', models.CharField(blank=True, help_text='Standard turnaround time (e.g. 2 hours, Same day, 24 hours).', max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls availability for ordering and public catalog listing.')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_tests', to='core.department')),
            ],
            options={
                'verbose_name': 'Diagnostic Test',
                'verbose_name_plural': 'Diagnostic Tests',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='diag_cat_active_idx')],
            },
        ),
    ]
