# Generated by Django 5.2.6 on 2026-10-08 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0027_diagnostictest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_type', models.CharField(choices=[('consultation', 'Doctor Consultation'), ('service', 'Clinical Service'), ('diagnostic', 'Diagnostic Test'), ('ward', 'IPD / Ward Daily Rate'), ('package', 'Health Package'), ('custom', 'Custom / Miscellaneous')], db_index=True, default='custom', max_length=24)),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('scope', models.CharField(blank=True, db_index=True, default='standard', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prices', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_prices', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-version', '-id'],
                'permissions': [('approve_price', 'Can approve, reject, or activate canonical prices')],
                'indexes': [models.Index(fields=['price_type', 'status', 'is_active'], name='price_type_stat_act_idx'), models.Index(fields=['content_type', 'object_id', 'status'], name='price_item_stat_idx'), models.Index(fields=['effective_from', 'effective_until'], name='price_eff_dates_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='canonical_price_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gte', models.F('effective_from')), _connector='OR'), name='canonical_price_dates_valid')],
            },
        ),
    ]
