# Generated by Django 5.2.6 on 2026-10-08 21:52

from django.conf import settings
from django.db import migrations, models


def backfill_admission_daily_rates(apps, schema_editor):
    Admission = apps.get_model("core", "Admission")
    for admission in Admission.objects.filter(daily_rate_snapshot__isnull=True).select_related("bed__ward").iterator():
        admission.daily_rate_snapshot = admission.bed.ward.daily_rate
        admission.save(update_fields=["daily_rate_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0028_canonical_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='daily_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Ward daily rate captured when the admission is created.', max_digits=12, null=True),
        ),
        migrations.RunPython(backfill_admission_daily_rates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('status', 'approved'), _connector='OR'), name='canonical_price_active_approved'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'price_type', 'scope', 'version'), name='canonical_price_item_scope_version_unique'),
        ),
    ]
