# Generated by Django 5.2.6 on 2026-10-09 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_harden_pricing_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('billing', 'Billing & Payments'), ('clinical', 'Clinical & Medical'), ('pharmacy', 'Pharmacy & Medication'), ('technical', 'Technical Support')], default='general', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_on_requester', 'Waiting on Requester'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'priority'], name='ticket_status_prio_idx'), models.Index(fields=['patient', 'status'], name='ticket_patient_status_idx'), models.Index(fields=['category', 'status'], name='ticket_category_status_idx'), models.Index(fields=['created_at'], name='ticket_created_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_progress', 'waiting_on_requester', 'resolved', 'closed'])), name='ticket_status_valid'), models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'normal', 'high', 'urgent'])), name='ticket_priority_valid'), models.CheckConstraint(condition=models.Q(('category__in', ['general', 'billing', 'clinical', 'pharmacy', 'technical'])), name='ticket_category_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['resolved', 'closed']), ('resolved_at__isnull', True), _connector='OR'), name='ticket_resolved_at_only_when_resolved'), models.CheckConstraint(condition=models.Q(('status', 'closed'), ('closed_at__isnull', True), _connector='OR'), name='ticket_closed_at_only_when_closed')],
            },
        ),
    ]
