# Generated by Django 5.2.6 on 2026-10-09 17:47

import core.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ticketmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=core.storage.PrivatePatientDocumentStorage(), upload_to='ticket_attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending Scan'), ('clean', 'Validated Clean'), ('rejected', 'Rejected / Infected')], default='clean', max_length=16)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='core.ticketmessage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_ticket_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='ticket_att_ticket_created_idx'), models.Index(fields=['scan_status'], name='ticket_att_scan_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('scan_status__in', ['pending', 'clean', 'rejected'])), name='ticket_attachment_scan_status_valid'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='ticket_attachment_size_positive')],
            },
        ),
    ]
