# Generated by Django 5.2.6 on 2026-10-09 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_secure_ticketing_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_total_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SLALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('policy_applied', 'Policy Applied'), ('target_adjusted', 'Target Adjusted'), ('clock_paused', 'Clock Paused'), ('clock_resumed', 'Clock Resumed'), ('breached', 'Breached')], max_length=32)),
                ('previous_due_at', models.DateTimeField(blank=True, null=True)),
                ('new_due_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_logs', to='core.ticket')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, choices=[('general', 'General Inquiry'), ('billing', 'Billing & Payments'), ('clinical', 'Clinical & Medical'), ('pharmacy', 'Pharmacy & Medication'), ('technical', 'Technical Support')], help_text='Null matches all categories.', max_length=32, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], help_text='Null matches all priorities.', max_length=16, null=True)),
                ('resolution_time_minutes', models.PositiveIntegerField(help_text='Target resolution time in minutes.')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, help_text='Null matches all departments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='core.department')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.slapolicy'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_due_at', 'status'], name='ticket_sla_due_idx'),
        ),
        migrations.AddIndex(
            model_name='slalog',
            index=models.Index(fields=['ticket', 'event'], name='sla_log_ticket_event_idx'),
        ),
        migrations.AddIndex(
            model_name='slapolicy',
            index=models.Index(fields=['is_active', 'priority', 'category'], name='sla_active_prio_cat_idx'),
        ),
    ]
